# config.py

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 800
FPS = 60

FONT_NAME = "freesansbold.ttf"

PLAYER_SPEED = 5
BOOST_SPEED = 10
BOOST_DURATION = 3 * FPS
BOOST_COOLDOWN = 30 * FPS

SEEKER_SPAWN_INTERVAL = 30 * FPS
SEEKER_SPEED_EASY = 2
SEEKER_SPEED_HARD = 4